### ISSUE TITLE
Title on titlebar is cut off (on left) (gnome 3.32)

### ISSUE THREAD

**Issue by VK2BEA** [B00merang-Project/OS-X-Leopard#3]
The title in the title bar of all the OS-X themes is cut off on the left.
i.e. it needs to be moved to the right.

I'm using gnome 3.32, cinnamon 4.2.3 on Fedora 30.

![](https://user-images.githubusercontent.com/11461036/62735192-a3a46a00-b9f8-11e9-8349-7e7ce81972ef.png)

The issue happens on all of these OSX themes. ( OS-X-Mavericks, OS-X-Leopard, OS-X-Yosemite )

The problem is in the file `metacity-1/metacity-theme-3.xml`.
The line in question is ...

`<title color="#4c4c4c" x="(0 max (width-title_width-mini_icon_width-IconTitleSpacing)) / 2 + mini_icon_width + IconTitleSpacing -72" y="(height - title_height) / 2 - 3"/>`

I think that mini_icon_width is undefined and so the evaluation breaks. 

Borrowing from another theme .. the fix is to replace the <title> line with:
```
        <title version="< 3.1"
               x="(0 `max` ((width - title_width) / 2))"
               y="(0 `max` ((height - title_height) / 2)) + 1"
               color="#4c4c4c" />
        <title version=">= 3.1"
               x="(0 `max` ((frame_x_center - title_width / 2) `min` (width - title_width)))"
               y="(0 `max` ((height - title_height) / 2)) + 1"
               ellipsize_width="width"
               color="#4c4c4c" />
```
 (same for the 'unfocused' case)

**Comment by Elbullazul** [comment]
can you please open a pull request with the correction?
