### ISSUE TITLE
Hack to surpress application name in mate

### ISSUE THREAD

**Issue by blue-devil-93** [B00merang-Project/OS-X-Leopard#4]
The vala appmenu of 19.10 ubuntu mate shows the window title when the title is very long p.ex gnu image manipulation program that vastes space of screen.
Thats why did create a small hack that only affects the menu when ticked the bold window title option. It surpresses the first menuitem label and this way only the menu is shown without window title.

`.-vala-panel-appmenu-bold > menuitem:nth-child(1) > label {
    font-size: 0 ;
    min-width: 0px;
    padding: 0px;
    margin:0px;
    background: yellow;
}
`

Maybe next year after February i might test the themes intensively and post suggestions.

**Comment by Elbullazul** [comment]
Sorry for being a little late.

Can you upload an example of the issue this code fixes? I'm not sureI fully understand it

**Comment by blue-devil-93** [comment]
![unpatched](https://user-images.githubusercontent.com/59343188/75605717-0a948800-5add-11ea-88bb-bd77abc27aeb.png)
![Bildschirmfoto zu 2020-02-29 10-17-18](https://user-images.githubusercontent.com/59343188/75605719-0bc5b500-5add-11ea-87cc-c800f30c263a.png)
![patched](https://user-images.githubusercontent.com/59343188/75605720-0c5e4b80-5add-11ea-8316-9c8e3fa3cfc6.png)

**Comment by blue-devil-93** [comment]
The thing is that the Application name does use much of the screen when using gimp or firefox.

Sry for the extremly late reply. 
Also the menu of selected text in panel appmenu is black instead of white on 19.10  but that i personally won`t fix.

**Comment by Elbullazul** [comment]
can you post an image with the hack disabled so I can see difference?

**Comment by blue-devil-93** [comment]
![without](https://user-images.githubusercontent.com/59343188/75707742-6450aa00-5cb7-11ea-991d-7f6c18597b58.png)

**Comment by Elbullazul** [comment]
upon reflection, I'd rather not implement this directly, since it's a feature removal, and themes shouldn't interfere with a program's features
