### ISSUE TITLE
Some elements are wrong in new GNOME

### ISSUE THREAD

**Issue by a0193143** [B00merang-Project/OS-X-Leopard#6]
Could you update for GNOME Shell and GTK 4.0?
It's a nice theme.
![2](https://user-images.githubusercontent.com/32773311/212553558-c9b67c94-249d-4402-8e65-c2ea7191185f.png)
![1](https://user-images.githubusercontent.com/32773311/212553562-3f624730-2664-4d83-ba3a-9f4ddf81d427.png)

**Comment by Elbullazul** [comment]
the shell theme hasn't been updated in a while, so I'll have to update it quite a bit.

surprised the GTK4 version looks that good to be honest, was expecting much worse. I'll fix those window buttons when i can, hopefully this week?

**Comment by Elbullazul** [comment]
[aae1183](https://github.com/B00merang-Project/OS-X-Leopard/commit/aae1183b3ef847795a59bb59a6f4b35cbe198f57) should fix this

**Comment by Elbullazul** [comment]
I'll create a separate issue for the shell theme
